# Generated by Django 3.0.8 on 2021-09-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=300)),
                ('dcto', models.IntegerField(default=0)),
                ('cantidadMinim', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.FamiliaProductos')),
            ],
        ),
    ]
