# Generated by Django 3.0.8 on 2021-09-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('duracion', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('mayoriaEdad', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('fechaLanzamiento', models.DateField(blank=True, null=True)),
                ('generos', models.ManyToManyField(to='Servicios.Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('generos', models.ManyToManyField(to='Servicios.Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('gratis', models.BooleanField(default=False)),
                ('precio', models.FloatField(default=0)),
                ('fechaLanzamiento', models.DateField()),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicios.Serie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubtitulosSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('archivoSub', models.FileField(upload_to='')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitulosPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('archivoSub', models.FileField(upload_to='')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Temporada'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('numLikes', models.IntegerField(default=0)),
                ('numVistas', models.IntegerField(default=0)),
                ('peliculas', models.ManyToManyField(to='Servicios.Pelicula')),
                ('series', models.ManyToManyField(to='Servicios.Serie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
